### ISSUE TITLE
Error installing pype32 with pip

### ISSUE THREAD

**Issue by MCKSysArgentina** [crackinglandia/pype32#3]
When trying to install pype32 with pip (Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32) an error occurs and the package cannot be installed.

The command was:
## 

D:\Python27>pip search pype32
pype32                    - Yet another Python library to read and write
                            PE/PE+ files.

D:\Python27>pip install pype32
Downloading/unpacking pype32
  Could not find a version that satisfies the requirement pype32 (from versions:
 0.1-alpha4)
Cleaning up...
No distributions matching the version for pype32
Storing debug log for failure in C:\Users\XXXX\pip\pip.log
## 

The pip.log file contents:
## 

Downloading/unpacking pype32
  Getting page https://pypi.python.org/simple/pype32/
  URLs to search for versions for pype32:
  * https://pypi.python.org/simple/pype32/
  Analyzing links from page https://pypi.python.org/simple/pype32/
    Found link https://pypi.python.org/packages/source/p/pype32/pype32-0.1-alpha4.zip#md5=4217494e5d8b9eb1d8aa637d8fe73dda (from https://pypi.python.org/simple/pype32/), version: 0.1-alpha4
  Ignoring link https://pypi.python.org/packages/source/p/pype32/pype32-0.1-alpha4.zip#md5=4217494e5d8b9eb1d8aa637d8fe73dda (from https://pypi.python.org/simple/pype32/), version 0.1-alpha4 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement pype32 (from versions: 0.1-alpha4)
Cleaning up...
  Removing temporary dir d:\systmp\pip_build_XXXX...
No distributions matching the version for pype32
Exception information:
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "D:\Python27\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "D:\Python27\lib\site-packages\pip\req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "D:\Python27\lib\site-packages\pip\index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for pype32
##

**Comment by MCKSysArgentina** [comment]
The package can be installed using: pip install --pre pype32
Since it's a pre-release.

Sorry about that. My mistake.
